import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { ThemeProvider } from "@/components/theme-provider";
import Nav from "@/components/nav";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SafeShare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <EdgeStoreProvider>
            <div className="flex relative min-h-screen flex-col">
              <Nav />
              <main className="flex-1 container mx-auto px-4 py-6">
                {children}
              </main>
              <footer className="border-t py-6 md:py-0">
                <div className="container mx-auto px-4 md h-14  items-center flex justify-between text-sm text-muted-foreground">
                  <p>
                    © {new Date().getFullYear()} SafeShare. All rights reserved.
                  </p>
                  <p className="text-sm text-muted-foreground">
                    Built with{" "}
                    <Link
                      href="https://nextjs.org"
                      target="_blank"
                      className="font-medium hover:text-primary transition-colors"
                    >
                      NextJS
                    </Link>
                  </p>
                </div>
              </footer>
            </div>
          </EdgeStoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
